# Generated by Django 3.1.2 on 2021-03-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_patient_regular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='burn_percentage',
        ),
    ]
