# Generated by Django 3.1.2 on 2021-03-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_patient_burn_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular',
            name='phone_number',
        ),
    ]
