# Generated by Django 3.1.2 on 2021-03-03 10:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_regular_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'مرد'), ('1', 'زن')], max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'اطلاع رسانی'), ('1', 'درمان یا بازتوانی'), ('2', 'برگزاری ها'), ('3', 'حرفه ای و کاری'), ('4', 'مالی و اقتصادی'), ('5', 'غیره...')], max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneHome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
