# Generated by Django 3.1.2 on 2021-03-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='burn_area',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='burn_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='burn_percentage',
            field=models.CharField(blank=True, choices=[('0', '10%'), ('1', '20%'), ('2', '30%')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='burn_place',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='burn_question',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='burn_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='burn_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='burn_type',
            field=models.CharField(blank=True, choices=[('0', 'نوع اول'), ('1', 'نوع دوم'), ('2', 'نوع سوم')], max_length=300),
        ),
    ]
