# Generated by Django 3.1.2 on 2021-03-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20210303_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='burn_percentage',
            field=models.CharField(blank=True, choices=[('0', 'درجه سوختگی'), ('1', '10%'), ('2', '20%'), ('3', '30%')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='burn_type',
            field=models.CharField(blank=True, choices=[('0', 'نوع سوختگی'), ('1', 'نوع اول'), ('2', 'نوع دوم'), ('3', 'نوع سوم')], max_length=300),
        ),
        migrations.CreateModel(
            name='BurnImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='burning_images')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
        ),
    ]
