# Generated by Django 3.1.2 on 2021-03-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20210303_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BurnImages',
        ),
    ]
