# Generated by Django 3.1.2 on 2021-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('help', models.CharField(choices=[('0', 'بنر\u200cهای مراسم گرامیداشت'), ('1', 'اطلاع\u200cرسانی در فضای دیجیتال'), ('2', 'تخصصی (درمان - بازتوانی)'), ('3', 'کاری و اجرایی')], max_length=300)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
