# Generated by Django 3.1.2 on 2021-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaztavaniService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DarmanService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estekhdam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('maharat', models.CharField(max_length=300)),
                ('companyName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('saatKari', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GholakService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='KargahService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Karyabi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('maharat', models.CharField(max_length=300)),
                ('percentage', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('saatKari', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MadadKariService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Marakez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markaz', models.CharField(max_length=50)),
                ('ostan', models.CharField(max_length=50)),
                ('shomare', models.CharField(max_length=30)),
                ('masool', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='Marakez_images')),
            ],
        ),
        migrations.CreateModel(
            name='MoshavereService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Namayande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markaz', models.CharField(max_length=50)),
                ('ostan', models.CharField(max_length=50)),
                ('shomare', models.CharField(max_length=30)),
                ('masool', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='Namayande_images')),
            ],
        ),
        migrations.CreateModel(
            name='Pezashkan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markaz', models.CharField(max_length=50)),
                ('ostan', models.CharField(max_length=50)),
                ('shomare', models.CharField(max_length=30)),
                ('takhasos', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='Pezeshkan_images')),
            ],
        ),
        migrations.CreateModel(
            name='PishgiriService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
